name: Preview on comment

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  preview:
    if: contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build web
        run: npm run build:web

      - name: Publish to CodeSandbox (static)
        id: publish
        run: |
          URL=$(npm run -s publish:csb:static)
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Write latest demo URL and commit
        env:
          URL: ${{ steps.publish.outputs.url }}
        run: |
          mkdir -p docs
          echo "$URL" > docs/latest-demo-url.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/latest-demo-url.txt
          git commit -m "chore(ci): update latest demo url [skip ci]" || echo "No changes to commit"
          git push || echo "Push failed (no remote or permissions)"

      - name: Comment with preview URL
        uses: actions/github-script@v7
        env:
          PREVIEW_URL: ${{ steps.publish.outputs.url }}
        with:
          script: |
            const url = process.env.PREVIEW_URL;
            const isPRReview = context.eventName === 'pull_request_review_comment';
            const issue_number = isPRReview ? context.payload.pull_request.number : context.payload.issue.number;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: `🚀 Live Preview: ${url}`,
            });

