name: Preview (Click-to-Link)

on:
  workflow_dispatch:  # Run from the Actions tab

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    # All "run:" steps execute inside the app folder
    defaults:
      run:
        working-directory: expo-ui-scaffold

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: expo-ui-scaffold/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Expo web
        run: npm run build:web

      # Publish the built site to GitHub Pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./expo-ui-scaffold/dist
